# Conexão com banco de dados principal (Virtual Gate)
DB_HOST = "10.100.117.118"
DB_PORT = "5432"
DB_NAME = "COPAFER_DW"
DB_USER = "postgres"
DB_PASSWORD = "#nfFbt"

# Conexão com banco de dados de Faturamento (COPAFER_DW)
FATURAMENTO_DB_HOST = "10.100.117.115"
FATURAMENTO_DB_PORT = "5432"
FATURAMENTO_DB_NAME = "DW"
FATURAMENTO_DB_USER = "postgres"
FATURAMENTO_DB_PASSWORD = "0AqTTu75BZ4xxHsP1421"

[PROD_DB]
PROD_DB_USER = "postgres"
PROD_DB_PASSWORD = "#nfFbt"
PROD_DB_HOST = "10.100.117.118"
PROD_DB_PORT = "5432"
PROD_DB_NAME = "COPAFER_PROD"

